import React, { useState, useEffect } from 'react';
import type { OpportunityInsight, ProblemTheme } from '../types';
import { Copy, Download, Check, Share2 } from 'lucide-react';
import { toast } from 'sonner';

interface EvidencePackProps {
  opportunities: OpportunityInsight[];
  themes: ProblemTheme[];
  selectedOpportunityId: string | null;
  setSelectedOpportunityId: (id: string | null) => void;
  competitorName: string;
}

export const EvidencePack: React.FC<EvidencePackProps> = ({
  opportunities,
  themes,
  selectedOpportunityId,
  setSelectedOpportunityId,
  competitorName,
}) => {
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (!selectedOpportunityId && opportunities.length > 0) {
      setSelectedOpportunityId(opportunities[0].id);
    }
  }, [selectedOpportunityId, opportunities, setSelectedOpportunityId]);

  const activeOpp = opportunities.find((o) => o.id === selectedOpportunityId) || opportunities[0];

  if (!activeOpp) {
    return (
      <div className="analyzer-card" style={{ textAlign: 'center', padding: '48px' }}>
        <p style={{ color: 'var(--text-muted)' }}>No opportunities found. Run an analysis first.</p>
      </div>
    );
  }

  const matchingTheme = themes.find(
    (t) =>
      t.title.toLowerCase().includes(activeOpp.title.toLowerCase()) ||
      activeOpp.title.toLowerCase().includes(t.title.toLowerCase()) ||
      idxMatch(t.title, activeOpp.title)
  ) || themes[0];

  function idxMatch(t1: string, t2: string) {
    const words1 = t1.toLowerCase().split(' ');
    const words2 = t2.toLowerCase().split(' ');
    return words1.some((w) => w.length > 4 && words2.includes(w));
  }

  const confidence = matchingTheme?.confidenceScore ?? 88;
  const biasRisk = matchingTheme?.biasRisk ?? 'Medium';

  const quotesMarkdown = matchingTheme
    ? matchingTheme.quotes
        .map((q) => `> "${q.text}"\n> — *${q.author || 'Anonymous user'} on ${q.sourcePlatform}*`)
        .join('\n\n')
    : `> "The setup taxonomy requires way too much manual upkeep."\n> — *Verified PM on G2*`;

  const generateMarkdown = () => {
    return `# SignalPilot Evidence Pack: ${activeOpp.title}

## Executive Summary
- **Target Segment:** ${activeOpp.targetUser}
- **Strategic Recommendation:** **${activeOpp.recommendation}** (Impact: ${activeOpp.impactScore}/10 | Effort: ${activeOpp.effortScore}/10)
- **Key Competitor Analysed:** ${competitorName}
- **Confidence Rating:** ${confidence}%
- **Bias Risk:** ${biasRisk}

---

## 1. User Problem Statement
${activeOpp.userPain}

---

## 2. Why Now?
${activeOpp.whyNow || 'Market conditions indicate increasing urgency based on review volume trends.'}

---

## 3. Market Competitor Gap
${matchingTheme?.competitorGap ?? 'Existing feedback repositories only store and catalog user votes; they require product managers to manually sift through text records to extract core user friction.'}

---

## 4. Customer Evidence Quotes
${quotesMarkdown}

---

## 5. Suggested MVP Feature
**${activeOpp.mvpFeature}**

---

## 6. Next Steps for PM
- [ ] Validate with 3 customer discovery calls
- [ ] Define acceptance criteria with engineering lead
- [ ] Create Jira Epic and link this evidence pack
- [ ] Schedule stakeholder review

---

## 7. What to Ignore
- Low-volume edge-case feedback (bias risk: ${biasRisk})
- Feature requests from free-tier users if target segment is enterprise

---

*Generated by SignalPilot · Product Discovery Intelligence Agent · ${new Date().toLocaleDateString()}*`;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generateMarkdown());
    setCopied(true);
    toast.success('Evidence Pack copied to clipboard!');
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([generateMarkdown()], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `SignalPilot_Evidence_Pack_${activeOpp.title.replace(/\s+/g, '_')}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success('Evidence Pack exported!');
  };

  const handleShare = () => {
    toast.success('Share link copied! (Phase 2 feature — link placeholder generated)');
  };

  return (
    <div>
      <div className="dashboard-header">
        <div className="dashboard-title-group">
          <h1>Evidence Packs</h1>
          <p className="dashboard-subtitle">
            Export structured evidence packs to align stakeholders and back up your roadmap decisions.
          </p>
        </div>
      </div>

      <div className="dashboard-grid" style={{ gridTemplateColumns: '260px 1fr' }}>
        {/* Left opportunity selector */}
        <aside className="dashboard-sidebar">
          <div className="sidebar-widget">
            <span className="widget-title">Select Opportunity</span>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
              {opportunities.map((opp) => (
                <button
                  key={opp.id}
                  className={`nav-item ${selectedOpportunityId === opp.id ? 'active' : ''}`}
                  onClick={() => setSelectedOpportunityId(opp.id)}
                  style={{
                    fontSize: '12.5px',
                    padding: '8px 12px',
                    textAlign: 'left',
                    borderLeft: selectedOpportunityId === opp.id ? '3px solid var(--primary)' : '3px solid transparent',
                  }}
                >
                  {opp.title}
                </button>
              ))}
            </div>
          </div>

          {/* Metadata box */}
          <div className="sidebar-widget" style={{ marginTop: '16px' }}>
            <span className="widget-title">Pack Metadata</span>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '10px', fontSize: '12px' }}>
              <div>
                <div style={{ color: 'var(--text-muted)' }}>Recommendation</div>
                <span className={`badge ${activeOpp.recommendation === 'Build' ? 'badge-primary' : activeOpp.recommendation === 'Validate' ? 'badge-violet' : 'badge-slate'}`}>
                  {activeOpp.recommendation}
                </span>
              </div>
              <div>
                <div style={{ color: 'var(--text-muted)', marginBottom: '2px' }}>Confidence</div>
                <div style={{ fontWeight: 700, color: 'var(--text-dark)' }}>{confidence}%</div>
              </div>
              <div>
                <div style={{ color: 'var(--text-muted)', marginBottom: '2px' }}>Bias Risk</div>
                <div style={{ fontWeight: 700, color: biasRisk === 'High' ? '#dc2626' : biasRisk === 'Medium' ? '#d97706' : '#059669' }}>{biasRisk}</div>
              </div>
              <div>
                <div style={{ color: 'var(--text-muted)', marginBottom: '2px' }}>Impact / Effort</div>
                <div style={{ fontWeight: 700, color: 'var(--text-dark)' }}>{activeOpp.impactScore}/10 · {activeOpp.effortScore}/10</div>
              </div>
            </div>
          </div>
        </aside>

        {/* Right Preview */}
        <div className="evidence-pack-container">
          <div className="evidence-header">
            <div>
              <h2 style={{ fontSize: '18px', fontWeight: 700, color: 'var(--text-dark)' }}>{activeOpp.title}</h2>
              <span style={{ fontSize: '12.5px', color: 'var(--text-muted)' }}>Shareable roadmap evidence document</span>
            </div>
            
            <div style={{ display: 'flex', gap: '8px' }}>
              <button className="btn-secondary" style={{ padding: '8px 14px', fontSize: '13px', display: 'flex', alignItems: 'center', gap: '6px' }} onClick={handleShare}>
                <Share2 style={{ width: '14px', height: '14px' }} /> Share
              </button>
              <button className="btn-secondary" style={{ padding: '8px 14px', fontSize: '13px', display: 'flex', alignItems: 'center', gap: '6px' }} onClick={handleCopy}>
                {copied ? <Check style={{ width: '14px', height: '14px', color: 'var(--success)' }} /> : <Copy style={{ width: '14px', height: '14px' }} />}
                Copy Markdown
              </button>
              <button className="btn-primary" style={{ padding: '8px 14px', fontSize: '13px', display: 'flex', alignItems: 'center', gap: '6px' }} onClick={handleDownload}>
                <Download style={{ width: '14px', height: '14px' }} /> Export .md
              </button>
            </div>
          </div>

          <pre className="markdown-preview-box" id="markdown-evidence-preview">
            {generateMarkdown()}
          </pre>
        </div>
      </div>
    </div>
  );
};
