import type { PlatformType, ProblemTheme, OpportunityInsight, CompetitorGapRow } from '../types';

export const MOCK_REVIEWS: Record<string, { platform: PlatformType; text: string; author: string; rating: number; sentiment: 'Positive' | 'Negative' | 'Neutral'; urgency: 'High' | 'Medium' | 'Low' }[]> = {
  Productboard: [
    {
      platform: 'G2',
      text: 'It brings structure to our feedback collection, but maintaining tags and linking comments to features takes too much time. Our PMs spend half their week just cleaning up tags.',
      author: 'Sarah M., Principal PM',
      rating: 3.5,
      sentiment: 'Neutral',
      urgency: 'High',
    },
    {
      platform: 'G2',
      text: 'The roadmap UI is beautiful and helps align stakeholders, but the AI tagging system is weak. It misses the real meaning behind user comments and groups everything under generic labels.',
      author: 'David K., Director of Product',
      rating: 3,
      sentiment: 'Negative',
      urgency: 'Medium',
    },
    {
      platform: 'Reddit',
      text: 'Productboard only works if the whole company follows a rigid process. If sales or CS stop tagging tickets, the database becomes a black hole of unorganized text.',
      author: 'u/pm_guru_99',
      rating: 2,
      sentiment: 'Negative',
      urgency: 'High',
    },
    {
      platform: 'Capterra',
      text: 'Good repository for feature requests, but it requires massive administrative overhead. We had to hire a dedicated coordinator just to manage the feedback backlog.',
      author: 'Elena R., VP of Product',
      rating: 3,
      sentiment: 'Negative',
      urgency: 'High',
    },
    {
      platform: 'G2',
      text: 'I love how we can link feedback directly to Jira. However, the synthesis phase is completely manual. I still have to read hundreds of tickets to extract the actual problem.',
      author: 'Marcus P., Product Manager',
      rating: 4,
      sentiment: 'Positive',
      urgency: 'Medium',
    },
  ],
  Canny: [
    {
      platform: 'G2',
      text: 'Upvoting is very engaging and our customers love the public roadmap, but popular requests are not always the most important. Loudest customers skew the voting count.',
      author: 'Jason L., Head of Product',
      rating: 3.5,
      sentiment: 'Neutral',
      urgency: 'High',
    },
    {
      platform: 'Reddit',
      text: 'We found that votes do not equal business impact. A minor UI change got 500 upvotes, while a critical enterprise compliance feature got only 3. We still need a way to weigh revenue impact.',
      author: 'u/saas_builder',
      rating: 3,
      sentiment: 'Negative',
      urgency: 'High',
    },
    {
      platform: 'Capterra',
      text: 'Managing duplicate requests is a nightmare at scale. Users keep posting the same feature request with slightly different words, and clean up is entirely manual.',
      author: 'Rachel T., Product Specialist',
      rating: 3,
      sentiment: 'Negative',
      urgency: 'Medium',
    },
    {
      platform: 'Product Hunt',
      text: 'Canny is incredibly easy to set up and start using immediately. But it lacks deep pain extraction. It just lists requests without helping us understand the underlying "why".',
      author: 'Tom S., SaaS Founder',
      rating: 4,
      sentiment: 'Positive',
      urgency: 'Medium',
    },
  ],
  Dovetail: [
    {
      platform: 'G2',
      text: 'Dovetail is fantastic for storing research and video transcriptions. However, translation into roadmap actions is difficult. Insights sit in silos separate from our engineering board.',
      author: 'Amanda G., UX Researcher',
      rating: 4,
      sentiment: 'Positive',
      urgency: 'Medium',
    },
    {
      platform: 'Reddit',
      text: 'Tagging transcriptions becomes extremely messy when research volume grows. We have 400 different tags and no taxonomy control. We need automated synthesis, not just manually highlighted text.',
      author: 'u/uxr_wizard',
      rating: 3,
      sentiment: 'Negative',
      urgency: 'High',
    },
    {
      platform: 'Capterra',
      text: 'Excellent transcription tool, but insights still need manual validation. It highlights where people said a keyword but doesnt help cluster the actual problem patterns automatically.',
      author: 'Chris D., Lead UX Researcher',
      rating: 3.5,
      sentiment: 'Neutral',
      urgency: 'Medium',
    },
  ],
  Aha: [
    {
      platform: 'G2',
      text: 'Extremely powerful tool for enterprise roadmapping and strategy definition. However, it is incredibly complex and heavy to set up. It took us 3 months to configure it properly.',
      author: 'Robert H., Enterprise PM',
      rating: 4,
      sentiment: 'Positive',
      urgency: 'Medium',
    },
    {
      platform: 'Capterra',
      text: 'The UI is cluttered and confusing for smaller teams. There are too many configuration fields. We just wanted a quick way to analyze competitor weaknesses, but Aha is too heavy.',
      author: 'Li Wei, Product Owner',
      rating: 2.5,
      sentiment: 'Negative',
      urgency: 'High',
    },
  ],
  'Jira Product Discovery': [
    {
      platform: 'G2',
      text: 'Since we already use Jira, the integration is seamless. But prioritization is still very manual. I have to create complex formulas and gather evidence manually to justify ideas.',
      author: 'Nico B., Technical PM',
      rating: 4,
      sentiment: 'Positive',
      urgency: 'Medium',
    },
    {
      platform: 'Reddit',
      text: 'JPD is a decent tool, but it doesn\'t help you find outside opportunities. It only helps you organize feedback you already captured. We need market review intelligence.',
      author: 'u/agile_coach',
      rating: 3.5,
      sentiment: 'Neutral',
      urgency: 'Medium',
    },
  ],
  Zomato: [
    {
      platform: 'Play Store',
      text: 'Delivery latency during peak hours is terrible. I waited 1.5 hours for food and it arrived cold. Swiggy does this much better.',
      author: 'Aman V.',
      rating: 2,
      sentiment: 'Negative',
      urgency: 'High',
    },
    {
      platform: 'Play Store',
      text: 'My order was missing items, and the customer support chatbot kept closing my ticket without offering a refund. This is extremely frustrating.',
      author: 'Neha S.',
      rating: 1,
      sentiment: 'Negative',
      urgency: 'High',
    },
    {
      platform: 'Reddit',
      text: 'Zomato Gold pricing has become a joke. Benefits are shrinking and they keep adding platform fees. I am switching to Swiggy One.',
      author: 'u/foodie_delhi',
      rating: 2.5,
      sentiment: 'Negative',
      urgency: 'Medium',
    },
    {
      platform: 'App Store',
      text: 'App crashes constantly on the checkout screen when using UPI. I had to retry three times and got charged twice. Fix this bug!',
      author: 'Rohan G.',
      rating: 1,
      sentiment: 'Negative',
      urgency: 'High',
    },
    {
      platform: 'Play Store',
      text: 'Zomato gold dining benefits are great. We got 40% off at our favorite restaurant in Mumbai. Discovery is very smooth.',
      author: 'Priya K.',
      rating: 4.5,
      sentiment: 'Positive',
      urgency: 'Low',
    },
  ],
  Internal: [
    {
      platform: 'Custom Website',
      text: 'Enterprise admins are struggling to export billing reports every month. They keep pinging support for manual exports.',
      author: 'Support Agent Logan',
      rating: 2,
      sentiment: 'Negative',
      urgency: 'High',
    },
    {
      platform: 'Custom Website',
      text: 'Invoice download keeps failing with 500 errors. We had 12 support tickets about this in the last 3 days.',
      author: 'Support Ticket #8291',
      rating: 1,
      sentiment: 'Negative',
      urgency: 'High',
    },
    {
      platform: 'Custom Website',
      text: 'Sales lost two deals this week because our reporting customization was not flexible enough. Customers want custom dashboards.',
      author: 'Account Executive Sarah',
      rating: 2,
      sentiment: 'Negative',
      urgency: 'High',
    },
    {
      platform: 'Custom Website',
      text: 'New users are confused after signup. The onboarding tutorial is too basic and doesn\'t show how to set up integrations.',
      author: 'User Interview (ID: 991)',
      rating: 3,
      sentiment: 'Neutral',
      urgency: 'Medium',
    },
    {
      platform: 'Custom Website',
      text: 'Our main analytics dashboard has too many numbers and no clear action points. It looks like a telemetry wall.',
      author: 'PM Internal Note',
      rating: 3,
      sentiment: 'Neutral',
      urgency: 'Low',
    },
  ],
};

export const MOCK_THEMES: Record<string, ProblemTheme[]> = {
  Productboard: [
    {
      id: 'pb_theme_1',
      title: 'Manual Tagging Is Still Painful',
      category: 'UX & Usability',
      summary: 'Product managers spend hours manually categorizing feedback, leading to administrative overhead and database clutter.',
      mentionCount: 84,
      platforms: ['G2', 'Capterra', 'Reddit'],
      severity: 'High',
      confidenceScore: 92,
      opportunityScore: 88,
      problemStatement: 'Product teams struggle to keep feedback organized because manual categorization and tagging are slow, subjective, and highly error-prone.',
      rootCause: 'Feedback repositories require PMs or support agents to read every comment and select tags from a custom taxonomy.',
      whyUsersCare: 'Crucial user signals get misclassified or buried under generic labels, leading to misinformed roadmap decisions.',
      competitorGap: 'Productboard offers tag auto-suggestions but still relies on users to manually parse and apply the taxonomy.',
      productOpportunity: 'Provide a client-side clustering engine that parses text and automatically highlights semantic patterns.',
      suggestedFeature: 'Auto-cluster incoming feedback into target problems and map them to structural features.',
      biasRisk: 'Medium',
      quotes: [
        {
          text: 'It brings structure to our feedback collection, but maintaining tags and linking comments to features takes too much time. Our PMs spend half their week just cleaning up tags.',
          sourcePlatform: 'G2',
          author: 'Sarah M., Principal PM',
          sentiment: 'Neutral',
          urgency: 'High',
        },
        {
          text: 'Good repository for feature requests, but it requires massive administrative overhead. We had to hire a dedicated coordinator just to manage the feedback backlog.',
          sourcePlatform: 'Capterra',
          author: 'Elena R., VP of Product',
          sentiment: 'Negative',
          urgency: 'High',
        },
      ],
    },
    {
      id: 'pb_theme_2',
      title: 'AI Summaries Lack Trust',
      category: 'AI Synthesis',
      summary: 'Automated AI summaries misinterpret specific feedback contexts and do not link to verifiable source quotes.',
      mentionCount: 42,
      platforms: ['G2', 'Product Hunt'],
      severity: 'Medium',
      confidenceScore: 84,
      opportunityScore: 76,
      problemStatement: 'Product Managers do not trust automated AI summaries because they lack transparency, omit key customer details, and lack direct evidence links.',
      rootCause: 'Summarization algorithms aggregate text without preserving contextual quotes or listing conflicting details.',
      whyUsersCare: 'PMs cannot bring black-box AI summaries to stakeholders because they cannot verify the raw quotes behind the statements.',
      competitorGap: 'AI summaries in existing systems are text paragraphs without drill-down verification layers.',
      productOpportunity: 'Generate traceable summaries where every claim is dynamically linked to the supporting review text.',
      suggestedFeature: 'Hover-to-reveal quote highlights and confidence scores for every synthesized theme.',
      biasRisk: 'Low',
      quotes: [
        {
          text: 'The roadmap UI is beautiful and helps align stakeholders, but the AI tagging system is weak. It misses the real meaning behind user comments and groups everything under generic labels.',
          sourcePlatform: 'G2',
          author: 'David K., Director of Product',
          sentiment: 'Negative',
          urgency: 'Medium',
        },
      ],
    },
    {
      id: 'pb_theme_3',
      title: 'Feedback Tools Require Too Much Maintenance',
      category: 'Process & Setup',
      summary: 'Configuring rigid taxonomies and onboarding team members leads to setup fatigue and high maintenance cost.',
      mentionCount: 65,
      platforms: ['Capterra', 'Reddit'],
      severity: 'High',
      confidenceScore: 88,
      opportunityScore: 82,
      problemStatement: 'Teams stop using feedback hubs because the initial configuration takes months, and keeping the taxonomy clean requires constant manual curation.',
      rootCause: 'Data architectures are designed around flat database schemas requiring rigorous hierarchy definition.',
      whyUsersCare: 'When tools are too complex, team adoption drops and product decisions revert back to guesswork.',
      competitorGap: 'Aha! and Productboard require significant manual taxonomy and workflow planning before use.',
      productOpportunity: 'A zero-config intelligence tool that extracts competitor insights instantly from public pages without setup.',
      suggestedFeature: 'Competitor URL analyzer that bypasses setup workflows and displays results in seconds.',
      biasRisk: 'Low',
      quotes: [
        {
          text: 'Productboard only works if the whole company follows a rigid process. If sales or CS stop tagging tickets, the database becomes a black hole of unorganized text.',
          sourcePlatform: 'Reddit',
          author: 'u/pm_guru_99',
          sentiment: 'Negative',
          urgency: 'High',
        },
      ],
    },
  ],
  Canny: [
    {
      id: 'canny_theme_1',
      title: 'Voting Does Not Equal Priority',
      category: 'Prioritization',
      summary: 'Public vote counts are skewed by loud customer segments and fail to reflect business impact or actual revenue indicators.',
      mentionCount: 112,
      platforms: ['G2', 'Reddit'],
      severity: 'High',
      confidenceScore: 90,
      opportunityScore: 85,
      problemStatement: 'PMs cannot rely on upvote counts because they represent feature requests from a vocal minority rather than high-value product opportunities.',
      rootCause: 'Public request forums weight all votes equally, lacking segmentation filters (enterprise vs. free tiers) or revenue mappings.',
      whyUsersCare: 'Building features based on public vote counts results in roadmaps that serve free users while neglecting enterprise contract blockers.',
      competitorGap: 'Canny displays vote counts prominently but lacks automatic business value and customer tier segmentation indicators.',
      productOpportunity: 'Correlate user pain with market opportunity scores, distinguishing between request volume and strategic impact.',
      suggestedFeature: 'Priority score formula that balances request frequency with platform diversity and sentiment urgency.',
      biasRisk: 'High',
      quotes: [
        {
          text: 'Upvoting is very engaging and our customers love the public roadmap, but popular requests are not always the most important. Loudest customers skew the voting count.',
          sourcePlatform: 'G2',
          author: 'Jason L., Head of Product',
          sentiment: 'Neutral',
          urgency: 'High',
        },
        {
          text: 'We found that votes do not equal business impact. A minor UI change got 500 upvotes, while a critical enterprise compliance feature got only 3. We still need a way to weigh revenue impact.',
          sourcePlatform: 'Reddit',
          author: 'u/saas_builder',
          sentiment: 'Negative',
          urgency: 'High',
        },
      ],
    },
    {
      id: 'canny_theme_2',
      title: 'Insights Do Not Connect to Roadmap Decisions',
      category: 'Roadmap Sync',
      summary: 'Feature request lists sit in functional isolation and do not link structural evidence directly to roadmap decisions.',
      mentionCount: 54,
      platforms: ['Product Hunt', 'Capterra'],
      severity: 'Medium',
      confidenceScore: 80,
      opportunityScore: 72,
      problemStatement: 'Feedback items remain disconnected from actual product sprints, leaving engineering teams without context on the core user problem.',
      rootCause: 'Feedback tools are designed as public intake boxes rather than roadmap-integrated decision tools.',
      whyUsersCare: 'Engineers build incorrect solutions because they receive raw feature requests rather than context-rich evidence packs.',
      competitorGap: 'Existing tools export CSV files or basic sync notifications but lack structured evidence sharing.',
      productOpportunity: 'Generate shareable roadmaps evidence packages that translate feature requests into structured "So What?" summaries.',
      suggestedFeature: 'Exportable Markdown Evidence Packs that link competitor gaps directly to MVP suggestions.',
      biasRisk: 'Medium',
      quotes: [
        {
          text: 'Canny is incredibly easy to set up and start using immediately. But it lacks deep pain extraction. It just lists requests without helping us understand the underlying "why".',
          sourcePlatform: 'Product Hunt',
          author: 'Tom S., SaaS Founder',
          sentiment: 'Positive',
          urgency: 'Medium',
        },
      ],
    },
  ],
  Zomato: [
    {
      id: 'zom_theme_1',
      title: 'Delivery Latency During Peak Hours',
      category: 'Delivery & Logistics',
      summary: 'Customers complain about long delivery delays and cold food during weekend peak hours, comparison-switching to Swiggy.',
      mentionCount: 242,
      platforms: ['Play Store', 'App Store', 'Reddit'],
      severity: 'High',
      confidenceScore: 95,
      opportunityScore: 92,
      problemStatement: 'Hungry customers experience flow disruption and extreme frustration because delivery runners are not dynamically pre-allocated during high-demand peak hours.',
      rootCause: 'Runner distribution algorithms depend on reactive bookings rather than predictive order clusters.',
      whyUsersCare: 'Cold food and long wait times directly lead to users ordering from alternative apps.',
      competitorGap: 'Swiggy One pre-allocates runners around high-volume restaurant clusters during weekends.',
      productOpportunity: 'Implement predictive runner pre-allocation around dense restaurant zones.',
      suggestedFeature: 'Dynamic peak-hour runner buffering based on historical restaurant prep times.',
      biasRisk: 'Low',
      quotes: [
        {
          text: 'Delivery latency during peak hours is terrible. I waited 1.5 hours for food and it arrived cold. Swiggy does this much better.',
          sourcePlatform: 'Play Store',
          author: 'Aman V.',
          sentiment: 'Negative',
          urgency: 'High',
        },
      ],
    },
    {
      id: 'zom_theme_2',
      title: 'Refund Delays For Missing Items',
      category: 'Customer Support',
      summary: 'Automated CS chatbots close tickets without verifying photo evidence, causing refund delays and customer churn.',
      mentionCount: 184,
      platforms: ['Play Store', 'Reddit'],
      severity: 'High',
      confidenceScore: 89,
      opportunityScore: 87,
      problemStatement: 'Customers struggle to get refunds for incomplete orders because support flows depend on auto-closing chatbot rules.',
      rootCause: 'CS automation prioritizes ticket closing speeds over user dispute resolution.',
      whyUsersCare: 'Paying for missing food with zero refund option feels like theft and permanently erodes user trust.',
      competitorGap: 'Competitor apps offer immediate wallet credit on uploading photo proofs of missing items.',
      productOpportunity: 'Build an automated photo-verification refund system.',
      suggestedFeature: 'Zero-agent automated wallet credit triggers upon receipt of verified item photos.',
      biasRisk: 'Medium',
      quotes: [
        {
          text: 'My order was missing items, and the customer support chatbot kept closing my ticket without offering a refund. This is extremely frustrating.',
          sourcePlatform: 'Play Store',
          author: 'Neha S.',
          sentiment: 'Negative',
          urgency: 'High',
        },
      ],
    },
    {
      id: 'zom_theme_3',
      title: 'App Crashes On Payment Screens',
      category: 'UX & Payments',
      summary: 'The checkout screen freezes during UPI handshakes, leading to double charges and failed orders.',
      mentionCount: 156,
      platforms: ['App Store', 'Play Store'],
      severity: 'High',
      confidenceScore: 92,
      opportunityScore: 89,
      problemStatement: 'Mobile users experience checkout drops because payment SDK handshakes fail in low-network areas.',
      rootCause: 'Checkout code requires synchronous server-side handshake responses without retry caching.',
      whyUsersCare: 'Double billing and order failures during hunger windows lead to high negative support load.',
      competitorGap: 'Unified UPI SDKs run offline background retries to verify transaction completion.',
      productOpportunity: 'Deploy a payment handshake cache and offline retry system.',
      suggestedFeature: 'UPI transaction state listener that holds order state for 30s during network dips.',
      biasRisk: 'Low',
      quotes: [
        {
          text: 'App crashes constantly on the checkout screen when using UPI. I had to retry three times and got charged twice. Fix this bug!',
          sourcePlatform: 'App Store',
          author: 'Rohan G.',
          sentiment: 'Negative',
          urgency: 'High',
        },
      ],
    },
  ],
  Dovetail: [
    {
      id: 'dt_theme_1',
      title: 'Tagging Bloat At Scale',
      category: 'Research Taxonomy',
      summary: 'PMs and researchers struggle to maintain tag consistency as customer interview transcriptions scale, leading to tag explosion.',
      mentionCount: 78,
      platforms: ['G2', 'Reddit'],
      severity: 'Medium',
      confidenceScore: 88,
      opportunityScore: 80,
      problemStatement: 'As transcription volume scales, the custom tags list explodes into hundreds of overlapping terms, making research tagging noisy and unscalable.',
      rootCause: 'Lack of taxonomy standardization or automated clustering of transcript text.',
      whyUsersCare: 'Siloed research reports get lost because nobody can navigate the cluttered tags catalog.',
      competitorGap: 'Dovetail lists tags but relies entirely on manual curation to prevent duplicates.',
      productOpportunity: 'Deploy a zero-config clustering engine that parses text and auto-assigns tags.',
      suggestedFeature: 'Dynamic Tag Hierarchy standardizer.',
      biasRisk: 'Medium',
      quotes: [
        {
          text: 'Tagging transcriptions becomes extremely messy when research volume grows. We have 400 different tags and no taxonomy control.',
          sourcePlatform: 'Reddit',
          author: 'u/uxr_wizard',
          sentiment: 'Negative',
          urgency: 'High',
        },
      ],
    },
    {
      id: 'dt_theme_2',
      title: 'Insights Disconnected From Sprints',
      category: 'Workflow Integration',
      summary: 'Synthesized UX research reports live in functional silos separate from the engineering backlog and PM sprint planning.',
      mentionCount: 52,
      platforms: ['G2', 'Capterra'],
      severity: 'High',
      confidenceScore: 90,
      opportunityScore: 84,
      problemStatement: 'Product decisions are made without referencing user research because research findings are stored separately from development boards.',
      rootCause: 'UX workspaces function as static knowledge bases instead of active roadmap decision integrations.',
      whyUsersCare: 'Engineers build solutions that fail to address the core user problems outlined in research reports.',
      competitorGap: 'Dovetail displays insights but does not sync roadmap-ready evidence with tickets.',
      productOpportunity: 'Provide an exportable evidence pack system that bridges research and roadmaps.',
      suggestedFeature: 'Roadmap evidence pack generation tool.',
      biasRisk: 'Low',
      quotes: [
        {
          text: 'Dovetail is fantastic for storing research and video transcriptions. However, translation into roadmap actions is difficult.',
          sourcePlatform: 'G2',
          author: 'Amanda G., UX Researcher',
          sentiment: 'Positive',
          urgency: 'Medium',
        },
      ],
    },
  ],
  Internal: [
    {
      id: 'int_theme_1',
      title: 'Invoice & Billing Report Failures',
      category: 'Core Services',
      summary: 'Enterprise clients are blocked from downloading invoices, resulting in manual support requests.',
      mentionCount: 94,
      platforms: ['Custom Website'],
      severity: 'High',
      confidenceScore: 96,
      opportunityScore: 90,
      problemStatement: 'Large clients complain about invoice downloading delays because PDF generators fail under high-volume database queries.',
      rootCause: 'Billing reporting code fetches full transactions synchronously instead of caching invoice states.',
      whyUsersCare: 'Delays in invoice submission block monthly accounting clearances, frustrating finance admins.',
      competitorGap: 'Internal systems lack robust reporting caches and zero-downtime PDF download handlers.',
      productOpportunity: 'Integrate an offline billing PDF rendering service.',
      suggestedFeature: 'Asynchronous PDF invoice compiler with email delivery.',
      biasRisk: 'Low',
      quotes: [
        {
          text: 'Invoice download keeps failing with 500 errors. We had 12 support tickets about this in the last 3 days.',
          sourcePlatform: 'Custom Website',
          author: 'Support Ticket #8291',
          sentiment: 'Negative',
          urgency: 'High',
        },
      ],
    },
    {
      id: 'int_theme_2',
      title: 'Lack of Custom Reporting',
      category: 'Features & Reporting',
      summary: 'Sales prospects drop out because SignalPilot dashboard customizations are too rigid for large companies.',
      mentionCount: 68,
      platforms: ['Custom Website'],
      severity: 'High',
      confidenceScore: 85,
      opportunityScore: 82,
      problemStatement: 'PMs cannot share dashboard telemetry with executives because telemetry layouts are static and cannot filter by custom metrics.',
      rootCause: 'Dashboard reporting depends on rigid template components.',
      whyUsersCare: 'SaaS decision makers reject the tool because they cannot extract custom compliance metrics.',
      competitorGap: 'Standard B2B SaaS dashboards do not allow layout customization.',
      productOpportunity: 'Deploy a drag-and-drop reporting panel with custom filter widgets.',
      suggestedFeature: 'Custom Dashboard Grid Builder.',
      biasRisk: 'Medium',
      quotes: [
        {
          text: 'Sales lost two deals this week because our reporting customization was not flexible enough. Customers want custom dashboards.',
          sourcePlatform: 'Custom Website',
          author: 'Account Executive Sarah',
          sentiment: 'Negative',
          urgency: 'High',
        },
      ],
    },
  ],
};

export const MOCK_OPPORTUNITIES: Record<string, OpportunityInsight[]> = {
  Productboard: [
    {
      id: 'pb_opp_1',
      title: 'Roadmap Evidence Pack Generator',
      userPain: 'PMs spend hours manually extracting customer quotes and compiling slideshows to defend their roadmap decisions to leadership.',
      evidence: '84 mentions of manual work and lack of evidence sharing in G2 reviews.',
      targetUser: 'B2B SaaS Product Managers facing stakeholder alignment bottlenecks.',
      whyNow: 'Stakeholders are demanding higher evidence levels and ROI proofs for roadmaps under tighter company budgets.',
      mvpFeature: 'Generate a structured Markdown evidence document with summaries, competitor gaps, and quotes in one click.',
      impactScore: 9,
      effortScore: 3,
      recommendation: 'Build',
    },
    {
      id: 'pb_opp_2',
      title: 'Cross-Platform Review Theme Clustering',
      userPain: 'Competitor feedback is scattered across G2, Capterra, and Reddit, making comprehensive market analysis exhausting.',
      evidence: 'Found feedback patterns split across 3 platforms with zero overlaps.',
      targetUser: 'Product Directors and researchers analyzing market landscapes.',
      whyNow: 'Review ecosystems are highly fragmented, and users post different complaint types on forums than on review sites.',
      mvpFeature: 'A centralized multi-platform URL analyzer that automatically detects source and clusters reviews client-side.',
      impactScore: 8,
      effortScore: 4,
      recommendation: 'Build',
    },
    {
      id: 'pb_opp_3',
      title: 'Bias Warning for Noisy Feedback',
      userPain: 'PMs accidentally build features for a single vocal client segment because raw volume charts hide demographic skew.',
      evidence: 'High concentration flags in 2 of the 3 top complaints.',
      targetUser: 'Enterprise SaaS PMs prioritizing roadmap backlogs.',
      whyNow: 'Customer success teams frequently escalate loudest-voice requests, overriding product strategy.',
      mvpFeature: 'A visual bias alert badge that triggers if 75% of feedback for a theme comes from a single customer channel.',
      impactScore: 7,
      effortScore: 2,
      recommendation: 'Validate',
    },
  ],
  Canny: [
    {
      id: 'canny_opp_1',
      title: 'Feature Request to User Pain Translator',
      userPain: 'Users request specific solutions (e.g., "Add CSV button") rather than explaining their root problem, leading to bad product designs.',
      evidence: '112 reviews highlighting voting noise and superficial requests.',
      targetUser: 'Growth and Core Product Managers looking for structural features.',
      whyNow: 'Teams are realizing that blindly building requested buttons leads to bloated codebases and low feature adoption.',
      mvpFeature: 'A rule-based keyword mapper that translates request tokens into underlying user pain statements.',
      impactScore: 9,
      effortScore: 4,
      recommendation: 'Build',
    },
    {
      id: 'canny_opp_2',
      title: 'Competitor Complaint Monitor',
      userPain: 'PMs do not know what complaints competitor users are posting in real-time, missing windows to capture dissatisfied users.',
      evidence: 'G2 and Reddit reviews frequently show users switching due to unaddressed complaints.',
      targetUser: 'Product Marketing and Growth PMs.',
      whyNow: 'Review platforms are growing rapidly and form the primary source of organic search traffic for buyers.',
      mvpFeature: 'A saved projects interface that tracks competitor URLs and alerts PMs when negative sentiment spikes.',
      impactScore: 8,
      effortScore: 5,
      recommendation: 'Validate',
    },
  ],
  Zomato: [
    {
      id: 'zom_opp_1',
      title: 'Predictive Peak-Hour Runner Buffering',
      userPain: 'Peak delivery runners are dispatched too late, causing customer orders to sit cold at restaurants during busy dinner times.',
      evidence: '242 reviews complaining about cold food and peak delivery lag.',
      targetUser: 'Logistics Operations and Delivery PMs.',
      whyNow: 'Customer retention is dropping due to a 12% rise in competitor delivery speeds.',
      mvpFeature: 'Pre-dispatch runners to high-volume zones 15 minutes before peak order forecasts.',
      impactScore: 9,
      effortScore: 5,
      recommendation: 'Build',
    },
    {
      id: 'zom_opp_2',
      title: 'Photo-Verification Auto Refunds',
      userPain: 'Customers are blocked from refunds for missing items because support chatbots close tickets automatically to hit response times.',
      evidence: '184 mentions of chatbot loop failures and delayed support refunds.',
      targetUser: 'Customer Experience and Support Ops PMs.',
      whyNow: 'Support overhead has increased by 18% due to follow-up tickets for unresolved missing item claims.',
      mvpFeature: 'A self-serve photo upload flow that issues automated wallet vouchers within 60 seconds.',
      impactScore: 8,
      effortScore: 3,
      recommendation: 'Build',
    },
    {
      id: 'zom_opp_3',
      title: 'UPI Payment Handshake Listener',
      userPain: 'Checkout freezes on payment gateways during poor connectivity, leading to double charges and abandoned carts.',
      evidence: '156 checkout payment drop complaints on iOS/Android stores.',
      targetUser: 'Checkout and Payment PMs.',
      whyNow: 'Double-billing claims have spiked, causing payment gateway penalties and processor churn.',
      mvpFeature: 'An Asynchronous payment listener that checks UPI txn status in the background.',
      impactScore: 9,
      effortScore: 4,
      recommendation: 'Validate',
    },
  ],
  Dovetail: [
    {
      id: 'dt_opp_1',
      title: 'Automated Research Synthesis',
      userPain: 'PMs spend hours manually reading transcriptions to tag and cluster recurring user problems.',
      evidence: '78 mentions of tagging bloat and manual research verification.',
      targetUser: 'UX Researchers and PMs conducting qualitative analysis.',
      whyNow: 'The volume of customer video interviews is growing, outstripping manual analysis capacity.',
      mvpFeature: 'Automatic transcript clustering and tag standardizer.',
      impactScore: 8,
      effortScore: 4,
      confidenceScore: 90,
      biasRisk: 'Low',
      recommendation: 'Build',
    },
    {
      id: 'dt_opp_2',
      title: 'Jira-Research Backlog Linker',
      userPain: 'Research findings sit isolated in a UX wiki instead of informing active developer sprints.',
      evidence: '52 mentions of disconnected research repositories and alignment issues.',
      targetUser: 'Technical Product Managers and Agile team leads.',
      whyNow: 'Agile teams want data proof linked directly to tickets to justify backlog priority.',
      mvpFeature: 'A button to sync structured evidence summaries directly to Jira epics.',
      impactScore: 9,
      effortScore: 3,
      confidenceScore: 85,
      biasRisk: 'Medium',
      recommendation: 'Build',
    },
  ],
  Internal: [
    {
      id: 'int_opp_1',
      title: 'Enterprise Billing Report Exporter',
      userPain: 'Enterprise finance managers are blocked from accounting clearances due to invoice download failures.',
      evidence: '94 complaints about invoice download timeout errors.',
      targetUser: 'Enterprise accounts and finance coordinators.',
      whyNow: 'Support overhead has increased due to manual invoice requests from enterprise customers.',
      mvpFeature: 'Offline PDF billing report rendering with asynchronous downloads.',
      impactScore: 8,
      effortScore: 2,
      confidenceScore: 95,
      biasRisk: 'Low',
      recommendation: 'Build',
    },
    {
      id: 'int_opp_2',
      title: 'Custom Dashboard Widget Builder',
      userPain: 'Sales lost high-value enterprise accounts due to rigid telemetry grids and lack of custom charts.',
      evidence: '68 mentions of report customization requests from prospects.',
      targetUser: 'Enterprise SaaS buyers and account executives.',
      whyNow: 'Competitors are launching modular analytics portals, making dashboard flexibility a deal-breaker.',
      mvpFeature: 'A drag-and-drop analytics grid allowing custom telemetry layouts.',
      impactScore: 9,
      effortScore: 5,
      confidenceScore: 80,
      biasRisk: 'High',
      recommendation: 'Validate',
    },
  ],
};

export const MOCK_GAP_MATRIX: CompetitorGapRow[] = [
  {
    competitorName: 'Productboard',
    whatUsersLike: 'Roadmaps alignment, feature structure, feedback repository.',
    commonComplaints: 'High manual tagging effort, setup complexity, weak automated tagging.',
    missingCapability: 'Automatic client-side final-mile synthesis and pain extraction.',
    signalPilotOpportunity: 'Auto evidence pack generation and decision-ready insight recommendations.',
  },
  {
    competitorName: 'Canny',
    whatUsersLike: 'Voting portals, public roadmaps, simple feature request intake.',
    commonComplaints: 'Upvotes do not represent business impact, duplication clutter.',
    missingCapability: 'Root pain mapping and automated priority reasoning metrics.',
    signalPilotOpportunity: 'Translating raw upvote requests into underlying user pain statements.',
  },
  {
    competitorName: 'Dovetail',
    whatUsersLike: 'Excellent research repository, transcription tags, video snippets.',
    commonComplaints: 'Tag bloat at scale, insights remain isolated from engineering.',
    missingCapability: 'Direct roadmap planning and feature prioritization integrations.',
    signalPilotOpportunity: 'Evidence-backed decision support directly exportable to development boards.',
  },
  {
    competitorName: 'Aha!',
    whatUsersLike: 'Powerful enterprise strategy mappings, comprehensive roadmap structures.',
    commonComplaints: 'Extremely heavy setup, UI configuration overload, slow onboarding.',
    missingCapability: 'Lightweight competitor review and zero-config market analysis.',
    signalPilotOpportunity: 'Instant URL-based competitor analysis that works in 5 seconds.',
  },
  {
    competitorName: 'Jira Product Discovery',
    whatUsersLike: 'Seamless sync with Jira tasks, good visual prioritization grids.',
    commonComplaints: 'Atlassian lock-in, manual evidence accumulation, simple filtering.',
    missingCapability: 'Automatic multi-platform external theme clustering.',
    signalPilotOpportunity: 'Gathering public competitor review feedback and finding market opportunities.',
  },
  {
    competitorName: 'ProductPlan',
    whatUsersLike: 'Simple, fast, presentation-friendly roadmap builder.',
    commonComplaints: 'No feedback linkage, manual roadmap updates, lack of data proof.',
    missingCapability: 'Direct connection to customer request databases or review sites.',
    signalPilotOpportunity: 'Providing a continuous opportunity and evidence feed to back up roadmap items.',
  },
  {
    competitorName: 'Enterpret',
    whatUsersLike: 'Enterprise feedback intelligence, deep custom classification models.',
    commonComplaints: 'Can feel enterprise-heavy for smaller teams, complex onboarding.',
    missingCapability: 'Lightweight competitor-review-first workflow.',
    signalPilotOpportunity: 'Fast market gap discovery for PMs.',
  },
];

export const MOCK_ZOMATO_GAP_MATRIX: CompetitorGapRow[] = [
  {
    competitorName: 'Swiggy',
    whatUsersLike: 'Good delivery times, Swiggy One membership discount, Dineout options.',
    commonComplaints: 'High delivery fees during rain, customer support uses auto-bots too much.',
    missingCapability: 'Direct item verification photo refunds.',
    signalPilotOpportunity: 'In-house auto verified refunds widget integration.',
  },
  {
    competitorName: 'Zepto',
    whatUsersLike: '10-minute delivery speed, high accuracy of grocery items.',
    commonComplaints: 'High pricing markup, items frequently out of stock.',
    missingCapability: 'Restaurant food delivery scaling.',
    signalPilotOpportunity: 'Real-time grocery-to-meal combo cross-selling.',
  },
  {
    competitorName: 'Blinkit',
    whatUsersLike: 'Massive catalog of household goods, fast deliveries.',
    commonComplaints: 'High delivery surcharge, bad fruit/vegetable quality occasionally.',
    missingCapability: 'Dine-in booking and food discovery feeds.',
    signalPilotOpportunity: 'Integration of community dining reviews with instant item delivery.',
  },
  {
    competitorName: 'Zomato (In-house)',
    whatUsersLike: 'Restaurant discovery, Zomato Gold loyalty program, user reviews.',
    commonComplaints: 'App crashes on payment checkout, delivery latency in peak times, refund delays.',
    missingCapability: 'Predictive runner distribution and automated duplicate review filter.',
    signalPilotOpportunity: 'Auto-crawl PlayStore/AppStore and filter duplicate complaints to assign developer tasks.',
  },
];
